require: rubocop-rspec

AllCops:
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Metrics/CyclomaticComplexity:
  Max: 8

Metrics/MethodLength:
  Max: 11

RSpec/MultipleExpectations:
  Exclude:
    - "spec/**/*"

RSpec/ExampleLength:
  Exclude:
    - "spec/**/*"

RSpec/NestedGroups:
  Exclude:
    - "spec/**/*"

RSpec/MultipleMemoizedHelpers:
  Exclude:
    - "spec/**/*"
